DBUser Class Reference
#include <DBUser.h>
Public Member Functions
DBUser ()
void addUser (User *user)
void addAdmin (Admin *admin)
void removeUser (User *user)
void editUser (User *user, std::string newNif)
User * findUser (std::string id)
void displayUsers ()
void saveUsers () const
void loadUsers ()
Private Attributes
std::set< User * > users
Detailed Description
Definition at line 11 of file DBUser.h.
Constructor & Destructor Documentation
DBUser()
DBUser::DBUser ()
Definition at line 6 of file DBUser.cpp.
{}
Member Function Documentation
addAdmin()
void DBUser::addAdmin (Admin * admin)
Definition at line 15 of file DBUser.cpp.
{
    users.insert(admin);
}
References users.
Referenced by loadUsers().
addUser()
void DBUser::addUser (User * user)
Definition at line 9 of file DBUser.cpp.
{
    users.insert(user);
}
References users.
Referenced by Dashboard::displayEditUsers(), and loadUsers().
displayUsers()
void DBUser::displayUsers ()
Definition at line 44 of file DBUser.cpp.
{
    for (auto& user : users) {
        std::cout << "ID: " << user->getId() << ", NIF: " << user->getNif() << std::endl;
    }
}
References users.
Referenced by Dashboard::displayEditUsers().
editUser()
void DBUser::editUser (User * user, std::string newNif)
Definition at line 27 of file DBUser.cpp.
{
    user->setNif(newNif);
}
References User::setNif().
Referenced by Dashboard::displayEditUsers().
findUser()
User * DBUser::findUser (std::string id)
Definition at line 33 of file DBUser.cpp.
{
    for (auto& user : users) { // Recorre todos los elementos del conjunto users (base de datos) con los usuarios
        if (user->getId() == id) { // Comprueba si el usuario de la iteracion tiene el mismo identificador que el proporcionado
            return user; // Si tiene el mismo identificador, devuelve el puntero al usuario, sino, continua buscando
        }
    }
    return nullptr; // Si no se encuentra ningun usuario con el mismo identificador, se evuelve un puntero a nullptr
}
References users.
Referenced by Dashboard::displayEditUsers(), and Dashboard::login().
loadUsers()
void DBUser::loadUsers ()
Definition at line 74 of file DBUser.cpp.
                  {
    std::ifstream file("users.dat");
    if (file.is_open()) {
        users.clear();
        std::string line;
        while (std::getline(file, line)) {
            std::istringstream iss(line);
            std::string id, nif, type;
            if (std::getline(iss, id, ',') &&
                std::getline(iss, nif, ',') &&
                std::getline(iss, type)) {
                try {
                    if (type == "U") {
                        User* user = new User(id, nif);
                        addUser(user);
                    } else if (type == "A") {
                        Admin* admin = new Admin(id, nif);
                        addAdmin(admin);
                    }
                } catch (const std::bad_alloc& e) {
                    // Manejo de falta de memoria
                    std::cout << "Error: No se pudo asignar memoria para crear un usuario" << std::endl;
                }
            }
        }
        file.close();
        std::cout << "Usuarios cargados desde el fichero" << std::endl;
    } else {
        std::cout << "No se pudo abrir el fichero" << std::endl;
    }
}
References addAdmin(), addUser(), and users.
Referenced by Dashboard::login().
removeUser()
void DBUser::removeUser (User * user)
Definition at line 21 of file DBUser.cpp.
{
    users.erase(user);
}
References users.
Referenced by Dashboard::displayEditUsers().
saveUsers()
void DBUser::saveUsers () const
Definition at line 53 of file DBUser.cpp.
                        {
    std::ofstream file("users.dat");
    if (file.is_open()) {
        for (auto& user : users) {
            file << user->getId() << "," << user->getNif();
            if (dynamic_cast<Admin*>(user) != nullptr) {
                file << ",A";
            } else {
                file << ",U";
            }
            file << std::endl;
        }
        file.close();
        std::cout << "Usuarios guardados en el fichero" << std::endl;
    } else {
        throw std::runtime_error("No se pudo abrir el fichero");
    }
}
References users.
Referenced by Dashboard::displayEditUsers().
Member Data Documentation
users
std::set<User*> DBUser::users [private]
Definition at line 24 of file DBUser.h.
Referenced by addAdmin(), addUser(), displayUsers(), findUser(), loadUsers(), removeUser(), and saveUsers().
The documentation for this class was generated from the following files:
include/DBUser.h
DBUser.cpp