Dashboard Class Reference
#include <Dashboard.h>
Public Member Functions
void initializeSensors ()
void addSensor (Sensor *sensor)
void login (DBUser &db)
void displayOptions (DBUser &db, User *currentUser)
void displayEditUsers (DBUser &db)
void displaySensors ()
Private Attributes
std::vector< Sensor * > sensors_
Detailed Description
Definition at line 9 of file Dashboard.h.
Member Function Documentation
addSensor()
void Dashboard::addSensor (Sensor * sensor)
Definition at line 36 of file Dashboard.cpp.
{
  sensors_.push_back(sensor);;
}
References sensors_.
Referenced by initializeSensors().
displayEditUsers()
void Dashboard::displayEditUsers (DBUser & db)
Definition at line 115 of file Dashboard.cpp.
                                      {
    int option;
    bool exit = false;
    
    while (!exit) {
        
        std::cout << "Opciones de edición de usuarios:" << std::endl;
        std::cout << "1. Mostrar usuarios" << std::endl;
        std::cout << "2. Añadir usuario" << std::endl;
        std::cout << "3. Eliminar usuario" << std::endl;
        std::cout << "4. Editar usuario" << std::endl;
        std::cout << "5. Guardar cambios y salir" << std::endl;
        try {
            std::cout << "Seleccione una opción:" << std::endl;
            std::cin >> option;
            if (std::cin.fail()) {
                throw std::invalid_argument("Debe ingresar un número.");
            }
            switch (option) {
                case 1: {
                    //Muestra todos los usuarios en la base de datos
                    std::cout << "Usuarios en la base de datos:" << std::endl;
                    db.displayUsers();
                    break;
                }
                case 2: {
                    //Crea un nuevo usuario y lo añade a la lista
                    std::string newId, newNif;
                    std::cout << "Introduzca el ID del nuevo usuario: ";
                    std::cin >> newId;
                    std::cout << "Introduzca el NIF del nuevo usuario: ";
                    std::cin >> newNif;
                    User* newUser = new User(newId, newNif);
                    db.addUser(newUser);
                    std::cout << "Usuario añadido correctamente." << std::endl;
                    break;
                }
                case 3: {
                    //Pide un id y elimina al user correspondiente
                    std::string IdToRemove;
                    std::cout << "Introduzca el ID del usuario a eliminar: ";
                    std::cin >> IdToRemove;
                    User* UserToRemove = db.findUser(IdToRemove);
                    if (UserToRemove != nullptr) {
                        db.removeUser(UserToRemove);
                        std::cout << "Usuario eliminado correctamente." << std::endl;
                    } else {
                        std::cout << "No se ha encontrado ningún usuario con tal identificador." << std::endl;
                    }
                    break;
                }
                case 4: {
                    //Permite editar el NIF de un usuario
                    std::string IdToEdit, newNif;
                    std::cout << "Introduzca el ID del usuario a editar: ";
                    std::cin >> IdToEdit;
                    User* UserToEdit = db.findUser(IdToEdit);
                    if (UserToEdit != nullptr) {
                        std::cout << "Introduzca el nuevo NIF del usuario: ";
                        std::cin >> newNif;
                        db.editUser(UserToEdit, newNif);
                        std::cout << "Usuario editado correctamente." << std::endl;
                    } else {
                        std::cout << "No se ha encontrado ningún usuario con tal identificador." << std::endl;
                    }
                    break;
                    }
                case 5: {
                    std::cout << "Guardando cambios y saliendo" << std::endl;
                    // Guarda los usuarios en users.dat
                    db.saveUsers();
                    exit = true;
                    break;
                }
            }
        } catch (const std::invalid_argument& e){
            std::cout << "Error de argumento: " << e.what() << std::endl;
            //Restablecer el estado de error
            std::cin.clear();
            std::cin.ignore();
        } catch (const std::ios_base::failure& e) {
            std::cout << "Error de lectura: " << e.what() << std::endl;
            //Restablecer el estado de error
            std::cin.clear();
            std::cin.ignore();
        }
    }
}
References DBUser::addUser(), DBUser::displayUsers(), DBUser::editUser(), DBUser::findUser(), DBUser::removeUser(), and DBUser::saveUsers().
Referenced by displayOptions().
displayOptions()
void Dashboard::displayOptions (DBUser & db, User * currentUser)
Definition at line 61 of file Dashboard.cpp.
                                                       {
    int option;
    while (true) {
        std::cout << "Opciones del sistema:" << std::endl;
        if (dynamic_cast<Admin*>(currentUser) != nullptr) {
            std::cout << "1. Mostrar opciones de edición de usuarios (Admin)" << std::endl;
        }
        std::cout << "2. Mostrar sensores" << std::endl;
        std::cout << "3. Salir" << std::endl;
        try {
            std::cout << "Introduzca una opción:" << std::endl;
            std::cin >> option;
            if (std::cin.fail()) {
                throw std::invalid_argument("Debe ingresar un número.");
            }
            switch (option) {
                case 1: {
                    if (dynamic_cast<Admin*>(currentUser) != nullptr) {
                        displayEditUsers(db);
                    } else {
                        std::cout << "Opción no válida para usuario normal." << std::endl;
                    }
                    break;
                }
                case 2: {
                    displaySensors();
                    break;
                }
                case 3: {
                    std::cout << "Saliendo del sistema" << std::endl;
                    return;
                }
                default: {
                    std::cout << "Opción no válida." << std::endl;
                    break;
                }
            }
        } catch (const std::invalid_argument& e) {
            std::cout << "Error de argumento: " << e.what() << std::endl;
            // Restablece el estado de error
            std::cin.clear();
            std::cin.ignore();
        } catch (const std::ios_base::failure& e) {
            std::cout << "Error de lectura: " << e.what() << std::endl;
            // Restablece el estado de error
            std::cin.clear();
            std::cin.ignore();
        }
    }
}
References displayEditUsers(), and displaySensors().
Referenced by login().
displaySensors()
void Dashboard::displaySensors ()
Definition at line 206 of file Dashboard.cpp.
                          {
    
    // Muestra la lista de sensores disponibles
    std::cout << "Seleccione el sensor del cual quiere ver los datos (o escriba 'salir' para salir):" << std::endl;
    for (size_t i = 0; i < sensors_.size(); ++i) {
        std::cout << i + 1 << ". " << sensors_[i]->getName() << std::endl;
    }
    // Lee la selección del usuario
    std::string option;
    std::cout << "Seleccione una opción:" << std::endl;
    std::cin >> option;
    while (option != "salir") {
        size_t index = std::stoul(option);
        if (index >= 1 && index <= sensors_.size()) {
            sensors_[index - 1]->getDate();
            sensors_[index - 1]->printDate();
        } else {
            std::cout << "Opción inválida" << std::endl;
        }
        std::cout << "Seleccione el sensor del que quiere informacion (o escriba 'salir' para salir):" << std::endl;
        for (size_t i = 0; i < sensors_.size(); ++i) {
            std::cout << i + 1 << ". " << sensors_[i]->getName() << std::endl;
        }
        std::cout << "Seleccione una opción:" << std::endl;
        std::cin >> option;
    }
}
References sensors_.
Referenced by displayOptions().
initializeSensors()
void Dashboard::initializeSensors ()
Definition at line 17 of file Dashboard.cpp.
                                  {
    // Crea los objetos de los diferentes sensores
    std::unique_ptr<AirQ> airq(new AirQ);
    std::unique_ptr<CamRGB> camrgb(new CamRGB);
    std::unique_ptr<CamTherm> camtherm(new CamTherm);
    std::unique_ptr<Temp> temp(new Temp);
    std::unique_ptr<Moisture> moisture(new Moisture);
    std::unique_ptr<Light> light(new Light);
    // Agrega los sensores a la lista de sensores del desplegable
    addSensor(airq.get());
    addSensor(camrgb.get());
    addSensor(camtherm.get());
    addSensor(temp.get());
    addSensor(light.get());
}
References addSensor().
Referenced by main().
login()
void Dashboard::login (DBUser & db)
Definition at line 42 of file Dashboard.cpp.
                           {
    //Pide al usuario que se autentique
    db.loadUsers();
    std::string id, nif;
    std::cout << "Introduzca su identificador: ";
    std::cin >> id;
    std::cout << "Introduzca su NIF: ";
    std::cin >> nif;
    User* currentUser = db.findUser(id);
    if (currentUser != nullptr && currentUser->getNif() == nif) {
        std::cout << "Bienvenido, usuario con identificador: " << currentUser->getId() << std::endl;
        displayOptions(db, currentUser);
    } else {
        std::cout << "ID o NIF incorrectos." << std::endl;
    }
}
References displayOptions(), DBUser::findUser(), User::getId(), User::getNif(), and DBUser::loadUsers().
Referenced by main().
Member Data Documentation
sensors_
std::vector<Sensor*> Dashboard::sensors_ [private]
Definition at line 19 of file Dashboard.h.
Referenced by addSensor(), and displaySensors().
The documentation for this class was generated from the following files:
include/Dashboard.h
Dashboard.cpp