User Class Reference
#include <User.h>
Public Member Functions
User (const std::string &id, const std::string &nif)
virtual ~User ()
std::string getId () const
std::string getNif () const
void setNif (const std::string &newNif)
Private Attributes
std::string id
std::string nif
Detailed Description
Definition at line 6 of file User.h.
Constructor & Destructor Documentation
User()
User::User (const std::string & id, const std::string & nif)
Definition at line 4 of file User.cpp.
    : id(id), nif(nif) // Se inicializan los atributos id y nif con los parametros proporcionados
{}
 User()
User::~User () [virtual]
Definition at line 8 of file User.cpp.
{}
Member Function Documentation
getId()
std::string User::getId () const
Definition at line 11 of file User.cpp.
                            {
    return id; // Devuelve el atributo identificador del usuario
}
References id.
Referenced by Dashboard::login().
getNif()
std::string User::getNif () const
Definition at line 15 of file User.cpp.
                             {
    return nif; // Devuelve el atributo identificador del usuario
}
References nif.
Referenced by Dashboard::login().
setNif()
void User::setNif (const std::string & newNif)
Definition at line 19 of file User.cpp.
                                         {
    nif = newNif; // Cambia el atributo nif con el nuevo Nif proporcionado al usuario
}
References nif.
Referenced by DBUser::editUser().
Member Data Documentation
id
std::string User::id [private]
Definition at line 17 of file User.h.
Referenced by getId().
nif
std::string User::nif [private]
Definition at line 18 of file User.h.
Referenced by getNif(), and setNif().
The documentation for this class was generated from the following files:
include/User.h
User.cpp